# Generated by Django 3.2.9 on 2022-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='software',
            field=models.ManyToManyField(to='users.Software', verbose_name='Используемые программы'),
        ),
    ]
