# Generated by Django 3.2.9 on 2022-01-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artwork_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkgallerypicture',
            name='art_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_images', to='users.artwork'),
        ),
    ]
