# Generated by Django 3.2.9 on 2022-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artwork_preview_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='about',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
