# Generated by Django 3.2.9 on 2022-02-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userachievement_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='square_avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='round_avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
