# Generated by Django 3.2.9 on 2022-02-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220210_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='square_avatar',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='round_avatar',
        ),
    ]
