# Generated by Django 3.2.9 on 2021-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='software',
        ),
        migrations.AddField(
            model_name='software',
            name='user',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
