# Generated by Django 3.2.9 on 2022-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_artwork_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_pic', models.ImageField(blank=True, upload_to='project_preview_pics', verbose_name='Аватар проекта')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=255, verbose_name='Описание проекта')),
                ('video_id', models.CharField(blank=True, max_length=255, verbose_name='id видео')),
                ('github_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на github')),
                ('appstore_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на appstore')),
                ('playmarket_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на playmarket')),
                ('status', models.CharField(choices=[('0', 'В разработке'), ('1', 'Завершён'), ('2', 'Конкурсная работа')], default='0', max_length=1, verbose_name='Состояние проекта')),
                ('developers', models.ManyToManyField(to='users.UserProfile', verbose_name='Разработчики')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images', verbose_name='Картинка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Картинка проекта',
                'verbose_name_plural': 'Картинки проекта',
            },
        ),
    ]
