# Generated by Django 3.2.9 on 2021-12-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_pic', models.ImageField(blank=True, upload_to='project_preview_pics')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('video_id', models.CharField(blank=True, max_length=255)),
                ('github_link', models.CharField(blank=True, max_length=255)),
                ('appstore_link', models.CharField(blank=True, max_length=255)),
                ('playmarket_link', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('0', 'In development'), ('1', 'Completed'), ('2', 'Contest job')], default='0', max_length=1)),
                ('developers', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project')),
            ],
        ),
    ]
