# Generated by Django 3.2.9 on 2022-02-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgallerypicture',
            name='compressed_image',
            field=models.ImageField(default='default.jpg', upload_to='compressed_images', verbose_name='Облегчённая картинка'),
        ),
    ]
