# Generated by Django 3.2.9 on 2022-01-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectgallerypicture',
            options={'verbose_name': 'Картинка проекта', 'verbose_name_plural': 'Картинки проекта'},
        ),
        migrations.AlterField(
            model_name='project',
            name='appstore_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на appstore'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(to='users.UserProfile', verbose_name='Разработчики'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на github'),
        ),
        migrations.AlterField(
            model_name='project',
            name='playmarket_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на playmarket'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_pic',
            field=models.ImageField(blank=True, upload_to='project_preview_pics', verbose_name='Аватар проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', 'В разработке'), ('1', 'Завершён'), ('2', 'Конкурсная работа')], default='0', max_length=1, verbose_name='Состояние проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='id видео'),
        ),
        migrations.AlterField(
            model_name='projectgallerypicture',
            name='image',
            field=models.ImageField(upload_to='gallery_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='projectgallerypicture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project', verbose_name='Проект'),
        ),
    ]
