# Generated by Django 3.2.9 on 2021-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_pic',
            field=models.ImageField(blank=True, upload_to='project_preview_pics'),
        ),
    ]
