# Generated by Django 3.2.9 on 2021-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectgallerypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
