# Generated by Django 3.2.9 on 2021-11-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgallerypicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project'),
        ),
    ]
