# Generated by Django 3.2.9 on 2021-11-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectgallerypicture_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgallerypicture',
            old_name='user',
            new_name='project',
        ),
    ]
