# Generated by Django 3.2.9 on 2021-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211130_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', 'In development'), ('1', 'Completed'), ('2', 'Contest job')], default='0', max_length=1),
        ),
    ]
