# Generated by Django 3.2.9 on 2021-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='software',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
