# Generated by Django 3.2.9 on 2021-11-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_pet_gallerypicture_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryPicture',
            new_name='UserGalleryPicture',
        ),
    ]
