# Generated by Django 3.2.9 on 2021-11-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211130_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='software',
            field=models.ManyToManyField(to='users.Software'),
        ),
    ]
