# Generated by Django 3.2.9 on 2021-11-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_user_projectgallerypicture_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='video_url',
            new_name='video_id',
        ),
    ]
