# Generated by Django 3.2.9 on 2021-11-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_video_url_project_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='appstore_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='playmarket_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
